---
- name: Setup vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC Setup output Variables
      include_vars: vars/output_vars

    - name: Import vprofile Stack Variables
      include_vars: vars/vprofilestack_setup

    - name: Import VPC setup Variables
      include_vars: vars/vpc_setup

    - name: create vprofile stack ec2 key
      ec2_key: 
        name: vprofilestack
        region: "{{region}}"
      register: vprofilekey_out

    - name: save private key to file
      copy:
        content: "{{vprofilekey_out.key.private_key}}"
        dest: "./vprofilestack.pem"
        mode: 0600
      when: vprofilekey_out.changed

    - name: Create Security group for Load Balancer
      ec2_group:
        name: vprofileELB-SG
        description: Allow port 80 from everywhere and all port within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vprofileELBSG_out

    - name: Security Group for Vprofile Stack
      ec2_group:
        name: vprofileStack-SG
        description: Allow port 22 from everywhere and all port within SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vprofileELBSG_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{bastionSGid}}"
      register: vprofileStackSG_out

    - name: Update Security group with its own SG id
      ec2_group:
        name: vprofileStackInternal-SG
        description: Allow port 22 with SG
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: {{vprofileStackSG_out.group_id}}
      register: vprofileStackInternal_out